/* Generated by lucy_config_generator — do not edit. */
#include "constant.h"
#include "joint.h"
#include "board.h"

void dump_config(void) {
  memset(boards, 0, sizeof(boards));

  board_t *board = &boards[0];
  board->init = &internal_init;
  board->on_joint_subscriber_update = &internal_on_joint_subscriber_update;

  joint_t *joint = board->data.internal.joints;

  /* left_a */
  joint->config.virtual_pin =         0;
  joint->config.physical_pin =        INTERNAL_SERVO_10;
  joint->config.servo_type =          SERVO_TYPE_270;
  joint->config.security_min_angle =  DEG_TO_RAD(0.0);
  joint->config.security_max_angle =  DEG_TO_RAD(270.0);
  joint->config.default_angle =       DEG_TO_RAD(135.0);
  joint->config.init_joint =          &internal_joint_init;
  joint->config.move_joint =          &internal_joint_move;
  joint++;
}